### ISSUE TITLE
NSE: failed to initialize the script engine:

### ISSUE THREAD

**Issue by kramse** [nerdalert/Dockerfiles#1]
When trying to use this docker image I get:
Starting Nmap 7.01 ( https://nmap.org ) at 2018-02-09 13:12 UTC
NSE: failed to initialize the script engine:
could not locate nse_main.lua
stack traceback:
	[C]: in ?

QUITTING!

I tried just running an "advanced script scan" with Nmap, the 2nd most common command I guess.

 nmap -A 10.80.0.163

**Comment by FieldOfRice** [comment]
Just add `nmap_scripts` after `nmap` to the Dockerfile. Afterwards also -A could be run.
